### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Tyarran**

### CODE REVIEW

**Comment by rcommande** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by rcommande** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by rcommande** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by Tyarran** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by Tyarran** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme
* [[#129](https://github.com/izberg-marketplace/izberg-microservices/pull/129)] Extracted some izberg helpers to new BaseResource



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by Tyarran** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating |  |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Comment by Tyarran** [comment]
`<Generated with ❤ by ChangelogGenerator>`
# Release Dev

<table>
	<tr>
		<th>Date</th>
		<td>2018-02-20 15:01:12</td>
	</tr>
	<tr>
		<th>Created by</th>
		<td>rcommande</td>
	</tr>
	<tr>
		<th>Action</th>
		<td>release</td>
	</tr>
	<tr>
		<th>Destination</th>
		<td>production</td>
	</tr>
</table>

# US
| Axosoft | Title | PR |
| - | - | - |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [7](https://github.com/rcommande/test-pr/pull/7) |
| [3592](https://izberg.axosoft.com/viewitem?id=3592&type=features&force_use_number=true) | JWT signin investigating | [129](https://github.com/izberg-marketplace/izberg-microservices/pull/129) |






# Miscellaneous
* [[#8](https://github.com/rcommande/test-pr/pull/8)] Add misc to readme



# IZBERG module upgrades

* izberg-marketplace/izberg-microservices `3.14.0` → `3.15.0` [diff](https://github.com/izberg-marketplace/izberg-microservices/compare/3.14.0...3.15.0)


`</Generated with ❤ by ChangelogGenerator>`

**Pull request closed without merging**
